Kumait w1
HackYourAssignment/React-class45 pull request #16
Opened 2023-12-13 23:41 UTC by 29Kumait

2023-12-19 13:40 UTC, robertoschiavone requested changes

2023-12-23 06:27 UTC, 29Kumait commented on server/server.js
Yes , I have got it, although it was quite straightforward only on the front end.
I finished the second task as well and the most of the 3rd for which I still have to Custom Hooks to reduce repetitive. thanks in advance so much looking forward for the second review. have a good day further.

2023-12-23 06:39 UTC, 29Kumait commented on week1/project/ecommerce/package.json
**After month of DB I would have thought deployment must be done by a server so I really did with two apart sides it really works and I rendered the category from the server as I remember; until I needed to move the server from being locally hosted then I failed. However I have better understanding about the task and it is already deployed on GibHubPages.**

2024-01-18 23:39 UTC, robertoschiavone commented
This PR does not meet all the requirements but you still solved the issues in the PRs for weeks 2 and 3, so I am taking the liberty to approve it anyway.

2024-01-18 23:47 UTC, robertoschiavone approved these changes

2024-07-15 16:13 UTC, closed without merging