islam-osman_Assignment w2
HackYourAssignment/React-class45 pull request #20
Opened 2023-12-19 14:27 UTC by IslamAltayeb

2023-12-26 20:46 UTC, durw4rd requested changes
Thank you for your work this week, Islam. I like how you handled the product detail page! However, you seem to have missed the requirements regarding the refactoring of the products overview page so I can't accept your work as it is now - please update the homepage so both categories and products are loaded from the API endpoints (remember to add the handling of loading and error states). In the process, please break the current single component to make sure each React component has only a single purpose in the application.

2023-12-26 20:46 UTC, durw4rd commented on week2/project/ecommerce/src/components/Product.js
Well done here, Islam! I like that you use the `useParams` hook, you included the handling of loading and error states, and your styling goes well beyond what was required for this homework.

2023-12-26 20:46 UTC, durw4rd commented on week2/project/ecommerce/src/components/Product.js
> +        }
What you wrote here is perfectly fine but wanted to show you another way this could be written which is a bit more concise:

```
if (!response.ok) {
  throw new Error('Error fetching product');
} 
const data = await response.json();
setProduct(data);
```

2023-12-26 20:46 UTC, durw4rd commented on week2/project/ecommerce/src/components/Products.js
> +import allCategories from '../fake-data/all-categories';
The fake data should be removed and the categories and products should be loaded via API. Have a look at the requirements for this week at the bottom of [this page](https://github.com/HackYourAssignment/React-class45/blob/main/week2/project/README.md).

2023-12-26 20:46 UTC, durw4rd commented on week2/project/ecommerce/src/components/Products.js
I won't comment further on this file as it needs to be completely refactored to meet the requirements of the week 2 homework. 
When refactoring your code, I would like you to break the categories and the list of product tiles into their own React components. This is to prevent having a single component that is responsible for several pieces of functionality and becomes too big & complex in the process.

2023-12-26 21:34 UTC, IslamAltayeb commented on week2/project/ecommerce/src/components/Products.js
thank you Michal for your reviewing my homework and your feedback, it's so useful actually 
i will try to finger it out

2023-12-26 21:34 UTC, IslamAltayeb commented on week2/project/ecommerce/src/components/Products.js
> +import allCategories from '../fake-data/all-categories';
oh, i forget to delete it, i will do it

2023-12-26 21:35 UTC, IslamAltayeb commented on week2/project/ecommerce/src/components/Product.js
> +        }
that is nicer, thanks for that

2024-01-04 11:08 UTC, durw4rd requested changes
Thank you for making the changes Islam! You clearly understand how to fetch data from an API but you missed some of the explicit requirements from the assignment for week two (you can check them [here](https://github.com/HackYourAssignment/React-class45/blob/main/week2/project/README.md)). 

Can you please make the two following updates:
- Fetch the info for category buttons from an API (https://fakestoreapi.com/products/categories) instead of hardcoding
- Update the logic for getting products so the category filter, if selected, is applied at the API level instead of client-side filtering. If you add the API routing logic inside the `getProducts` function and call `getProducts` when one of the category buttons is clicked, this will allow you to get rid of the `filterProducts` altogether but feel free to explore other approaches too!

Sorry for being a bit pedantic on this but given your work so far, it hopefully shouldn't take too much of your time.

2024-01-04 14:42 UTC, IslamAltayeb commented
thank you Michal for your feedback I will try to do my best to finalize it,
by the way, I have an issue with deploying, i tried many times with netlify, render 
as you see I used npm run build but still i can't deploy it 
so could you help me with that?

2024-01-05 16:07 UTC, durw4rd requested changes
Hello Islam, thank you for your continued work on the assignment! 
The project is generally moving in the right direction but some of the changes also led to a loss of existing functionality (it's not possible to easily un-select a product category now) and especially the content of the Products.js file is now quite hard to read. 
I've left comments with suggestions, please have a look and let me know if anything is not clear. 
Regarding the deployment of your app, what issues/errors are you seeing? Are you trying to create an automatic deploy from the GitHub repository or are you deploying manually? I just tried manually deploying your app using the [Netlify's Drop](https://app.netlify.com/drop). After dropping the 'build' folder of your app, it got deployed without any problem here: https://659825e1b1117020f848cff9--hilarious-vacherin-92fad4.netlify.app/.

2024-01-06 22:41 UTC, IslamAltayeb commented on week2/project/ecommerce/src/components/Products.js
thank you for your feedback i'm learning a lot from that
i will try to do my best to figure it out

2024-01-10 13:30 UTC, durw4rd approved these changes
Thanks for implementing the changes Islam! I've added a couple of suggestions for improvements but I'll accept your work as is!

2024-01-10 13:30 UTC, durw4rd commented on week2/project/ecommerce/src/components/Products.js
> +  const getProducts = async (category = null) => {
I'd recommend adding `setLoading(true);` on line 14, before the try/catch statement - that way, the loading state is displayed every time you change the category filter as well.

2024-01-10 13:30 UTC, durw4rd commented on week2/project/ecommerce/src/components/Buttons.js
Ideally, you should add the handling of loading/error states also for this component - this would be similar to other components, for example, the `Products` component. 

```
const [loading, setLoading] = useState(true);
const [error, setError] = useState(null);
[...]
const fetchCategories = async () => {
      try {
        const response = await fetch('https://fakestoreapi.com/products/categories');
        if (response.ok) {
          const data = await response.json();
          setCategories(data);
        } else {
          setError('Failed to fetch categories');
          throw new Error('Failed to fetch categories');
        }
      } catch (err) {
        console.log(err);
        setError('Failed to fetch categories');
      } finally {
        setLoading(false);
      }
    };
[...]
return (
    <div className="buttons d-flex justify-content-center mp-4 pb-5 flex-column flex-sm-row gap-2 align-items-center">
      {loading ? (
          <div className="col-12 text-center">
            <h3>Loading...</h3>
          </div>
        ) : error ? (
          <div className="col-12 text-center">Error: {error}</div>
        ) : (categories.map((category, index) => (
        <button
          key={index}
          className={`btn btn-outline-dark me-2 ${selectedCategory === category ? 'active' : ''}`}
          onClick={() => handleCategoryClick(category)}
        >
          {category}
        </button>
      )))}
    </div>
  );
```

2024-01-31 02:22 UTC, closed without merging